# hardware-configuration.nix
#
# Purpose: Hardware configuration auto-generated by nixos-generate-config for popcat19-dedede0
#
# hardware-configuration.nix
#
# Purpose: Minimal hardware configuration for shimboot dedede board
{ lib, ... }:
{
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
