{ lib, pkgs, ... }:

let
  # Import wallpaper.nix to inherit its functionality
  wallpaperModule = import ../hypr_config/wallpaper.nix { inherit lib pkgs; };

  # Walrs package from overlays
  walrs = pkgs.callPackage ../overlays/walrs.nix {};

  # System templates directory (if exists)
  systemTemplates = "/usr/share/walrs/templates";

in {
  home.packages = [ walrs ];

  # Inherit wallpaper images from wallpaper.nix
  home.file.".config/walrs/wallpapers" = {
    source = wallpaperModule.wallpaperDir;
    recursive = true;
  };

  # Create templates directory and kitty template
  home.file.".config/walrs/templates/colors-kitty.conf" = {
    text = ''
      # Kitty colors generated by walrs
      background {background}
      foreground {foreground}
      cursor {cursor}

      color0 {color0}
      color1 {color1}
      color2 {color2}
      color3 {color3}
      color4 {color4}
      color5 {color5}
      color6 {color6}
      color7 {color7}
      color8 {color8}
      color9 {color9}
      color10 {color10}
      color11 {color11}
      color12 {color12}
      color13 {color13}
      color14 {color14}
      color15 {color15}
    '';
  };

  # Basic walrs configuration
  home.file.".config/walrs/config" = {
    text = ''
      # Walrs configuration
      # Add configuration options here as needed
    '';
  };

  # Expose wallpaper images for use in scripts
  home.sessionVariables = {
    WALLPAPER_DIR = "${wallpaperModule.wallpaperDir}";
    WALRS_CACHE_DIR = "$HOME/.cache/wal";
  };
}