#!/bin/bash
# Script to help obtain Syncthing device IDs for both machines

echo "Syncthing Device ID Helper Script"
echo "================================="
echo ""
echo "This script will help you obtain the device IDs for both nixos0 and surface0."
echo ""
echo "Step 1: Make sure Syncthing is running on both machines"
echo "Step 2: Run the following commands on each machine to get their device IDs:"
echo ""
echo "On nixos0 (popcat19-nixos0):"
echo "  curl -s http://localhost:8384/rest/system/config | jq -r '.deviceID'"
echo ""
echo "On surface0 (popcat19-surface0):"
echo "  curl -s http://localhost:8384/rest/system/config | jq -r '.deviceID'"
echo ""
echo "Alternatively, you can check the Syncthing web UI at http://localhost:8384"
echo "The device ID is displayed in the top right corner of the web interface."
echo ""
echo "Once you have both device IDs, update the syncthing_config/system.nix file:"
echo "  - Replace 'NIXOS0-DEVICE-ID-PLACEHOLDER' with nixos0's actual device ID"
echo "  - Verify that surface0's device ID is correct: 5HCOSXJ-N56FEEI-VIUQRUV-S2LCQTM-AZK4DSC-5AOSNYF-7RQTTZM-6VOJYAN"
echo ""
echo "After updating the device IDs, rebuild and restart the systems:"
echo "  nixos-commit-rebuild-push 'Update Syncthing device IDs'"
echo ""