# Window Rules for Hyprland
# ==========================

{
  wayland.windowManager.hyprland.settings = {
    # Window rules v2
    windowrulev2 = [
      # General rules
      "suppressevent maximize, class:.*"
      "nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0"
      "minsize 1024 600,class:^(org.pulseaudio.pavucontrol)$"

      # Opacity rules - matching kitty's opacity and blur
      "opacity 0.85 0.85,class:^(code-oss)$"
      "opacity 0.85 0.85,class:^([Cc]ode)$"
      "opacity 0.85 0.85,class:^(code-url-handler)$"
      "opacity 0.85 0.85,class:^(code-insiders-url-handler)$"
      "opacity 0.85 0.85,class:^(kitty)$"
      "opacity 0.85 0.85,class:^(org.kde.dolphin)$"
      "opacity 0.85 0.85,class:^(org.kde.ark)$"
      "opacity 0.85 0.85,class:^(nemo)$"
      "opacity 0.85 0.85,class:^(nautilus)$"
      "opacity 0.85 0.85,class:^(nwg-look)$"
      "opacity 0.85 0.85,class:^(qt5ct)$"
      "opacity 0.85 0.85,class:^(qt6ct)$"
      "opacity 0.85 0.85,class:^(kvantummanager)$"
      "opacity 0.85 0.75,class:^(org.pulseaudio.pavucontrol)$"
      "opacity 0.85 0.75,class:^(blueman-manager)$"
      "opacity 0.85 0.75,class:^(nm-applet)$"
      "opacity 0.85 0.75,class:^(nm-connection-editor)$"
      "opacity 0.85 0.75,class:^(org.kde.polkit-kde-authentication-agent-1)$"
      "opacity 0.85 0.75,class:^(polkit-gnome-authentication-agent-1)$"
      "opacity 0.85 0.75,class:^(org.freedesktop.impl.portal.desktop.gtk)$"
      "opacity 0.85 0.75,class:^(org.freedesktop.impl.portal.desktop.hyprland)$"
      "opacity 0.75 0.75,class:^([Ss]team)$"
      "opacity 0.75 0.75,class:^(steamwebhelper)$"
      "opacity 0.75 0.75,class:^([Ss]potify)$"
      "opacity 0.75 0.75,initialTitle:^(Spotify Free)$"
      "opacity 0.75 0.75,initialTitle:^(Spotify Premium)$"
      "opacity 0.90 0.90,class:^(com.github.rafostar.Clapper)$"
      "opacity 0.85 0.85,class:^(com.github.tchx84.Flatseal)$"
      "opacity 0.85 0.85,class:^(hu.kramo.Cartridges)$"
      "opacity 0.85 0.85,class:^(com.obsproject.Studio)$"
      "opacity 0.85 0.85,class:^(gnome-boxes)$"
      "opacity 0.85 0.85,class:^(vesktop)$"
      "opacity 0.85 0.85,class:^(discord)$"
      "opacity 0.85 0.85,class:^(WebCord)$"
      "opacity 0.85 0.85,class:^(ArmCord)$"
      "opacity 0.85 0.85,class:^(app.drey.Warp)$"
      "opacity 0.85 0.85,class:^(net.davidotek.pupgui2)$"
      "opacity 0.85 0.85,class:^(yad)$"
      "opacity 0.85 0.85,class:^(Signal)$"
      "opacity 0.85 0.85,class:^(io.github.alainm23.planify)$"
      "opacity 0.85 0.85,class:^(io.gitlab.theevilskeleton.Upscaler)$"
      "opacity 0.85 0.85,class:^(com.github.unrud.VideoDownloader)$"
      "opacity 0.85 0.85,class:^(io.gitlab.adhami3310.Impression)$"
      "opacity 0.85 0.85,class:^(io.missioncenter.MissionCenter)$"
      "opacity 0.85 0.85,class:^(io.github.flattool.Warehouse)$"
      "opacity 0.88 0.76,class:^(steam_app_1920960)$,title:^(MainWindow)$,xwayland:1"

      # Floating rules
      "float,class:^(org.kde.dolphin)$,title:^(Progress Dialog — Dolphin)$"
      "float,class:^(org.kde.dolphin)$,title:^(Copying — Dolphin)$"
      "float,title:^(About Mozilla Firefox)$"
      "float,class:^(firefox)$,title:^(Picture-in-Picture)$"
      "float,class:^(firefox)$,title:^(Library)$"
      "float,class:^(kitty)$,title:^(top)$"
      "float,class:^(kitty)$,title:^(btop)$"
      "float,class:^(kitty)$,title:^(htop)$"
      "float,class:^(vlc)$"
      "float,class:^(mpv)$"
      "float,class:^(kvantummanager)$"
      "float,class:^(qt5ct)$"
      "float,class:^(qt6ct)$"
      "float,class:^(nwg-look)$"
      "float,class:^(org.kde.ark)$"
      "float,class:^(org.pulseaudio.pavucontrol)$"
      "float,class:^(blueman-manager)$"
      "float,class:^(nm-applet)$"
      "float,class:^(nm-connection-editor)$"
      "float,class:^(org.kde.polkit-kde-authentication-agent-1)$"
      "float,class:^(Signal)$"
      "float,class:^(com.github.rafostar.Clapper)$"
      "float,class:^(app.drey.Warp)$"
      "float,class:^(net.davidotek.pupgui2)$"
      "float,class:^(yad)$"
      "float,class:^(eog)$"
      "float,class:^(org.kde.gwenview)$"
      "float,class:^(io.github.alainm23.planify)$"
      "float,class:^(io.gitlab.theevilskeleton.Upscaler)$"
      "float,class:^(com.github.unrud.VideoDownloader)$"
      "float,class:^(io.gitlab.adhami3310.Impression)$"
      "float,class:^(io.missioncenter.MissionCenter)$"
      "float, class:Waydroid"
      "float,class:^(xdg-desktop-portal-gtk)$"
      "float,class:^(org.keepassxc.KeePassXC)$,title:^(Password Generator)$"
      "float,class:^(keepassxc)$,title:^(Password Generator)$"
    ];

    # Window rules v1 (legacy)
    windowrule = [
      "float,title:^(Open)$"
      "float,title:^(Choose Files)$"
      "float,title:^(Save As)$"
      "float,title:^(Confirm to replace files)$"
      "float,title:^(File Operation Progress)$"
    ];
  };
}