# monitors.conf
#
# Purpose: Monitor configuration for nixos0 multi-monitor setup

monitor=DP-2, 1920x1080@165.00, 0x0, 1
monitor=HDMI-A-1, 1920x1080@60.00, 1920x-560, 1, transform, 1
monitor=DP-3, 1920x1080@60.00, 3000x0, 1
monitor=,preferred,auto,auto

workspace = 1, monitor:DP-2, default:true
workspace = 2, monitor:HDMI-A-1, default:true
workspace = 3, monitor:DP-3, default:true

# Map OpenTabletDriver virtual pen to the Gaomon display
device {
    name = opentabletdriver-virtual-artist-tablet
    output = DP-3
}
