# hardware-configuration.nix
#
# Purpose: Hardware configuration auto-generated by nixos-generate-config for popcat19-aarch640
#
# hardware-configuration.nix
#
# Purpose: Stub hardware configuration for the generic aarch64 host
#
# Replace this with the output of nixos-generate-config on the target device.
{ lib, modulesPath, ... }:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [ ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-label/NIXOS_SD";
    fsType = "ext4";
  };

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
