name: Nix Flake CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  flake-check:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Install Nix with flakes support
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v12
        with:
          extra-conf: |
            experimental-features = nix-command flakes

      # 3. Setup cache for faster builds
      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v7

      # 4. Clean up any existing result links
      - name: Clean up result links
        run: rm -f result result-*

      # 5. Validate flake structure
      - name: Check flake
        run: nix flake check -L

      # 6. Build the system configuration without linking
      - name: Build NixOS configuration
        run: nix build --no-link .#nixosConfigurations.popcat19-nixos0.config.system.build.toplevel -L

  flake-build:
    runs-on: ubuntu-latest
    needs: flake-check
    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Install Nix with flakes support
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v12
        with:
          extra-conf: |
            experimental-features = nix-command flakes

      # 3. Setup cache for faster builds
      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v7

      # 4. Clean up any existing result links
      - name: Clean up result links
        run: rm -f result result-*

      # 5. Build flake outputs without linking
      - name: Build flake outputs
        run: nix build --no-link -L